var mongoose = require('mongoose');
var Schema = mongoose.Schema; 

/**
 * Record Schema
 */
var Record = new Schema({
    UNITID: Number,
    INSTNM: String,
    ADDR: String,
    CITY: String,
    STABBR: String,
    ZIP: Number,
    FIPS: Number
    CHFNM: Number,
    OBEREG: String,
    CHFTITLE: String,
    GENTELE: Number,
    FAXTELE: Number,
    EIN: Number,
    OPEID: Number,
    OPEFLAG: Number,
    WEBADDR: String,
    ADMINURL: String,
    FAIDURL: String,
    APPLURL: String,
    NPRICURL: String,
    SECTOR: Number,
    ICLEVEL: Number,
    CONTROL: Number,
    HLOFFER: Number,
    UGOFFER: Number,
    GROFFER: Number,
    HDEGOFR1: Number,
    DEGGRANT: Number,
    HBCU: Number,
    HOSPITAL: Number,
    MEDICAL: Number,
    TRIBAL: Number,
    LOCALE: Number,
    OPENPUBL: Number,
    ACT: Number,
    NEWID: Number,
    DEATHYR: Number,
    CLOSEDAT: Number,
    CYACTIVE: Number,
    PSEFLAG: Number,
    PSET4FLG: Number,
    RPTMTH: Number,
    IALIAS: String,
    INSTCAT: Number,
    CCBASIC: Number,
    CCIPUG: Number,
    CCIPGRAD: Number,
    CCUGPROF: Number,
    CCSIZSET: Number,
    CARNEGIE: Number,
    INSTSIZE: Number,
    CBSA: Number,
    CBSATYPE: Number,
    CSA: Number,
    NECTA: Number,
    F1SYSTYP: Number,
    F1SYSNAM: String,
    F1SYSCOD: Number,
    COUNTYCD: Number,
    COUNTYNM: String,
    CNGDSTCD: Number,
    LONGITUD: Number,
    LATITUDE: Number,

});

mongoose.model('Record', Record); 